name: build

on: [push]

jobs:
  test:
    runs-on: macOS-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Run tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 29
        script: ./gradlew check jacocoTestReport

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
